# these yml files are being read by Github automatically, 
# and instruct Github for workflows

# indentations are tab based

name: deploy-container

on:
  push:
    branches:
      - master # on push to anything inside master branch
    paths:
      - 'packages/container/**' # only start the workflows if there is any commit in container folder

defaults:
  run:
    working-directory: packages/container # run all command inside container folder

jobs:
  build:
    runs-on: ubuntu-latest

    stesp:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run build

      - uses: shinyinc/action-aws-cli@v1.2
      - run: aws s3 sync dist s3://${{ secrects.AWS_S3_BUCKET_NAME }}/container/latest
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY_ID: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}
          AWS_DEFAULT_REGION: ""

